### ISSUE TITLE
[issue]

### ISSUE THREAD

**Issue by KadeDev** [galaxy119/DiscordIntegration#8]
The issue with the latest version and latest exiled.

Exception:
`[2020-04-13 05:52:58.368 +02:00] [ERROR] [EXILED]: Plugin Discord Integration threw an exception while enabling System.TypeLoadException: Could not resolve type with token 010000af (from typeref, class/assembly OnElevatorInteract, )
  at EXILED.PluginManager.OnEnable () [0x00019] in <dbc43024854b48d89695df941486a713>:0`

This wasn't on my server but it should be looked into.

**Comment by galaxy119** [comment]
This is caused by using the newest version of the plugin on an outdated version of EXILED. This is not a bug in the plugin, it's a bug in the users brain.

**Comment by KadeDev** [comment]
@galaxy119 look at the post, he was using the latest version of fucking everything.

**Comment by galaxy119** [comment]
Could not resolve type with token 010000af (from typeref, class/assembly OnElevatorInteract, ) at EXILED.PluginManager.OnEnable ()

Means it couldn't resolve the method OnElevatorInteract, because it couldn't find the type for that method - IE: ElevatorInteractionEvent - IE: He wasn't using 1.9.3+ of EXILED.

When i load 1.9.0, I get this exact error.
When I load 1.9.3+, I get no errors.
