### ISSUE TITLE
# breaks logs

### ISSUE THREAD

**Issue by FreeJuicebox** [galaxy119/DiscordIntegration#9]
I'm not sure where to start as I am fairly new to programming and can't properly read the complexity of the code however if you use # it completely breaks the logs. Anything that is before the # will be erased from existence. Not only does this make discord usernames break and only show their 4 number handle but also allows for mods running commands and completely erasing their tracks by putting a # after their command.

**Comment by galaxy119** [comment]
This is due to the way the game handles RA messages - the messages have to be prefixes with "<source>#" followed by the message.
Therefore it's assumed that if there's a ``#`` in the message, everything before it is the <message source> - which is not always the case.

You can blame NW's shitty implementation of the RA message system - since they could have easilly just made the method take 2 seperate strings <source> <message> instead of a single one (<source#message>) that gets split like it does now, or for their stupid idea of including the #xxxx numbers from peoples Discord names in their in-game name without accounting for this issue.

Either way it can't realistically be fixed except by them.

**Comment by galaxy119** [comment]
It should be noted that EXILED itself keeps an RA command log in the same location as your plugin config file (~/.config/EXILED or %AppData%\EXILED) for each server.
You can use this to ~~thanos snap~~ punish those who are exploiting the bug to erase command logs - as this log doesn't work the same way DiscordIntegration logs do, and will not erase logs with a # at the end. (also not to mention most commands will not function properly if you put a # at the end of them anyways)
